CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email_lower ON users (LOWER(email));

CREATE TABLE IF NOT EXISTS vaults (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  data JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE vaults ADD COLUMN IF NOT EXISTS data JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE vaults DROP COLUMN IF EXISTS salt;
ALTER TABLE vaults DROP COLUMN IF EXISTS iv;
ALTER TABLE vaults DROP COLUMN IF EXISTS ciphertext;
